version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
 #  - run:
  #  command: |
   #    ssh-keyscan 13.59.53.222 >> ~/.ssh/known_hosts


     - run: |
            sudo apt update && sudo apt install sshpass -y
             sshpass -p $sanju ssh ubuntu@52.32.223.142 'ls'
             
     - run: |
            sshpass -p $test1mode ssh ubuntu@13.58.242.170 'ls -ltr' 
            
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
