version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
      - add_ssh_keys:
          fingerprints:
            - "eb:a8:88:b9:7e:0e:92:51:10:d0:c9:9b:24:b6:06:34"   
      - run: |
           sudo apt update && sudo apt install sshpass -y
           sshpass -p $universe ssh  root@13.233.254.72 -p 22 'ls -lhtr'
             
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
