version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
 #  - run:
  #  command: |
   #    ssh-keyscan 13.59.53.222 >> ~/.ssh/known_hosts

     - run: |
        #     sudo apt update && sudo apt install sshpass -y
             sshpass -p $USER_PASS11 ssh ubuntu@3.17.57.40 'sudo docker images'
             
     - run: |
            sshpass -p $useast_11 ssh ubuntu@207.246.95.150 'docker images'
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
