version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
 #  - run:
  #  command: |
   #    ssh-keyscan 13.59.53.222 >> ~/.ssh/known_hostsp


     - run: |            
  #       if [[ "sshpass -p $test1mode ssh ubuntu@13.58.242.170 'ls -ltr'" == 0 ]]
         if [ -n "sshpass -p $test1mode ssh ubuntu@13.58.242.170 'ls -ltr'" ]; then
            echo $?
         fi
        
     - run: |            
          if [[ "sshpass -p $sanju ssh ubuntu@52.32.223.142 'ls'" != 0 ]]
         then 
            echo "testup1"test:
  post:
    - >
      if [ -n "${RUN_NIGHTLY_BUILD}" ]; then
        ./bin/run-functional-tests.sh ${FUNCTIONAL_TEST_TARGET};
      fi

            echo $?
         fi   
      
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
