version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
   - run: |
    #  command: |
       ssh-keyscan 18.222.134.76 >> ~/.ssh/known_hosts 'ls'

    # - run: |
         #   sudo apt update && sudo apt install sshpass -y
     #        ssh ubuntu@18.222.134.76 'ls'
             
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
