version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
      - add_ssh_keys:
          fingerprints:
            - "a2:aa:03:8b:1d:f9:63:28:d8:f3:df:ae:a3:a3:23:92"   
      - run: |
           ssh-keyscan -p 502 $HOST >> ~/.ssh/known_hosts
           ssh -vv root@13.233.254.72 -p 502 'ls -lhtr'
             
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
