version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
#   - run: |
 #     command: |
  #     ssh-keyscan 18.222.134.76 >> ~/.ssh/known_hosts'ls'
  #  - run: |
   #         ssh root@useast-0.iogamemaker.com 'ls'
      - run: |
           ssh ubuntu@18.223.238.178 'ls'
   vultr_deploy_fetchsh1:
    machine: true
    steps:
#   - run: |
 #     command: |
  #     ssh-keyscan 18.222.134.76 >> ~/.ssh/known_hosts'ls'
  #  - run: |
   #         ssh root@useast-0.iogamemaker.com 'ls'
      - run: |
           ssh ubuntu@18.218.146.77 'ls'
             
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
      - vultr_deploy_fetchsh1:
         filters:
           branches:
             only:
               - master
