version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - add_ssh_keys:
          fingerprints:
            - "eb:a8:88:b9:7e:0e:92:51:10:d0:c9:9b:24:b6:06:34"    
      - run: |
            sudo apt update && sudo apt install sshpass -y
            sshpass -p $universe ssh  ssh  root@13.233.254.72 -p 22 'ls -lhtr'
# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
