version: 2
jobs:
 vultr_deploy_fetchsh:
   machine: true
   steps:
      - run: |
           ssh root@113.233.254.72 'ls -lhtr'
             
workflows:
 version: 2
 rolling_update:
   jobs:
     - vultr_deploy_fetchsh:
         filters:
           branches:
             only:
               - master
